// swift-tools-version: 5.9
//
// Phase L10 L1 — pairing-first slice. Pure-Swift library: an Xcode app
// target wraps it (`TARSCompanionApp.swift` to be generated by
// `xcodegen` / Xcode). Builds + tests cross-platform on macOS so CI
// can validate the network/crypto layer without a simulator.

import PackageDescription

let package = Package(
    name: "TARSCompanion",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "TARSCompanion", targets: ["TARSCompanion"]),
    ],
    targets: [
        .target(
            name: "TARSCompanion",
            path: "Sources/TARSCompanion"
        ),
        .testTarget(
            name: "TARSCompanionTests",
            dependencies: ["TARSCompanion"],
            path: "Tests/TARSCompanionTests"
        ),
    ]
)
