"""Tests for the W4-PR3 workshop debrief renderer.

End-to-end: spin up real attendees, drive paper sessions, then
render the bundle. Asserts on the structure of the output (we
don't snapshot the full markdown — that's brittle — but we DO
snapshot the headings, the leaderboard table shape, and key
phrases).
"""

from __future__ import annotations

import asyncio
import os
import tempfile
from pathlib import Path

import pytest

from backend.core.algotrade import get_registry
from backend.core.algotrade.exec import (
    OrderIntent,
    OrderType,
    Side,
    get_runtime,
    reset_runtime,
)
from backend.core.algotrade.lab import (
    render_workshop_debrief,
    reset_lab_store,
    get_lab_store,
)
from backend.core.algotrade.recipes import list_recipes, load_recipe
from backend.core.domains.packs.algotrade.lab_actions import (
    LAB_ACTIONS,
    lab_workshop_debrief_action,
)


@pytest.fixture
def tars_home():
    with tempfile.TemporaryDirectory() as tmp:
        old = os.environ.get("TARS_ALGOTRADE_HOME")
        os.environ["TARS_ALGOTRADE_HOME"] = tmp
        reset_runtime()
        reset_lab_store()
        try:
            yield Path(tmp)
        finally:
            reset_runtime()
            reset_lab_store()
            if old is None:
                del os.environ["TARS_ALGOTRADE_HOME"]
            else:
                os.environ["TARS_ALGOTRADE_HOME"] = old


def _bar(*, ts: float, price: float, instrument: str) -> dict:
    return {
        "ts": ts,
        "open": price,
        "high": price,
        "low": price,
        "close": price,
        "volume": 1.0,
        "instrument": instrument,
    }


def _drive_round_trip(
    sandbox_id: str,
    *,
    open_price: float,
    close_price: float,
    instrument: str = "BINANCE:BTCUSDT",
) -> str:
    name = list_recipes()[0]
    fp = get_registry().put(load_recipe(name)).fingerprint
    runtime = get_runtime()
    wiring = runtime.start_paper_session(
        strategy_fingerprint=fp,
        instrument=instrument,
        sandbox_id=sandbox_id,
    )

    async def run() -> None:
        await wiring.router.submit(
            OrderIntent.make(
                strategy_fingerprint=fp,
                instrument=instrument,
                side=Side.BUY,
                qty=1.0,
                type=OrderType.MARKET,
            )
        )
        await wiring.adapter.on_bar(
            _bar(ts=1.0, price=open_price, instrument=instrument),
            instrument=instrument,
        )
        await wiring.router.submit(
            OrderIntent.make(
                strategy_fingerprint=fp,
                instrument=instrument,
                side=Side.SELL,
                qty=1.0,
                type=OrderType.MARKET,
            )
        )
        await wiring.adapter.on_bar(
            _bar(ts=2.0, price=close_price, instrument=instrument),
            instrument=instrument,
        )

    asyncio.run(run())
    return wiring.session.session_id


# --------------------------------------------------------- pack surface


def test_debrief_action_is_registered(tars_home: Path) -> None:
    ids = [a.id for a in LAB_ACTIONS]
    assert "lab_workshop_debrief" in ids


def test_debrief_action_unknown_workshop(tars_home: Path) -> None:
    res = asyncio.run(
        lab_workshop_debrief_action({"workshop_id": "ws_missing"})
    )
    assert res["ok"] is False
    assert res["error"] == "workshop_not_found"


def test_debrief_action_requires_workshop_id(tars_home: Path) -> None:
    res = asyncio.run(lab_workshop_debrief_action({}))
    assert res["ok"] is False
    assert res["error"] == "missing_workshop_id"


# --------------------------------------------------------- renderer


def test_debrief_unknown_workshop_raises(tars_home: Path) -> None:
    with pytest.raises(KeyError):
        render_workshop_debrief("ws_missing")


def test_debrief_empty_workshop_renders_skeleton(tars_home: Path) -> None:
    store = get_lab_store()
    store.create_workshop(name="Empty", workshop_id="ws_empty")
    debrief = render_workshop_debrief("ws_empty")
    md = debrief.markdown
    assert md.startswith("# Workshop debrief — Empty")
    assert "## Workshop" in md
    assert "## Leaderboard" in md
    assert "_no attendees enrolled yet._" in md
    assert "_Generated by TARS algotrade_" not in md
    assert "Generated by TARS algotrade" in md  # in footer


def test_debrief_renders_full_bundle_with_sessions(tars_home: Path) -> None:
    store = get_lab_store()
    store.create_workshop(name="Cresco", workshop_id="ws_c")
    a = store.enroll(
        workshop_id="ws_c",
        display_name="Alice",
        attendee_id="att_alice",
    )
    b = store.enroll(
        workshop_id="ws_c",
        display_name="Bob",
        attendee_id="att_bob",
    )
    _drive_round_trip(a.sandbox_id, open_price=100.0, close_price=120.0)
    _drive_round_trip(b.sandbox_id, open_price=100.0, close_price=80.0)

    debrief = render_workshop_debrief("ws_c")

    # Workshop header.
    assert "ws_c" in debrief.markdown
    assert "## Workshop" in debrief.markdown
    # Leaderboard table.
    assert "| Rank | Attendee | Sessions" in debrief.markdown
    assert "| 1 | Alice |" in debrief.markdown
    assert "| 2 | Bob |" in debrief.markdown
    # Per-attendee sections in rank order.
    alice_idx = debrief.markdown.find("### Alice")
    bob_idx = debrief.markdown.find("### Bob")
    assert 0 < alice_idx < bob_idx
    # Each attendee section embeds at least one session report
    # (top heading pushed three levels deeper: # → ####).
    assert "#### Session" in debrief.markdown


def test_debrief_skip_session_reports(tars_home: Path) -> None:
    store = get_lab_store()
    store.create_workshop(name="HeadlineOnly", workshop_id="ws_h")
    a = store.enroll(
        workshop_id="ws_h", display_name="Alice", attendee_id="att_a"
    )
    _drive_round_trip(a.sandbox_id, open_price=100.0, close_price=110.0)

    debrief = render_workshop_debrief(
        "ws_h", include_session_reports=False
    )
    # Headlines still there.
    assert "### Alice" in debrief.markdown
    # No embedded session report.
    assert "##### Session" not in debrief.markdown
    assert "Headline metrics" not in debrief.markdown


def test_debrief_consensus_returns_valid_severity(tars_home: Path) -> None:
    """The aggregated consensus must be one of the three valid
    severity levels — even for a session that doesn't trip any
    voice (which produces ``info`` as the default consensus)."""

    store = get_lab_store()
    store.create_workshop(name="Sev", workshop_id="ws_s")
    bob = store.enroll(
        workshop_id="ws_s", display_name="Bob", attendee_id="att_bob"
    )
    _drive_round_trip(bob.sandbox_id, open_price=100.0, close_price=50.0)

    debrief = render_workshop_debrief("ws_s")
    bob_block = next(a for a in debrief.attendees if a.attendee.attendee_id == "att_bob")
    assert bob_block.council_consensus in {"info", "warn", "alert"}
    # The bundled markdown surfaces the consensus too.
    assert (
        f"**Council consensus**: {bob_block.council_consensus}"
        in debrief.markdown
    )


def test_debrief_to_dict_round_trips(tars_home: Path) -> None:
    store = get_lab_store()
    store.create_workshop(name="RT", workshop_id="ws_rt")
    store.enroll(
        workshop_id="ws_rt",
        display_name="Solo",
        attendee_id="att_solo",
    )
    debrief = render_workshop_debrief("ws_rt")
    d = debrief.to_dict()
    assert d["workshop"]["workshop_id"] == "ws_rt"
    assert d["leaderboard"]["workshop_id"] == "ws_rt"
    assert isinstance(d["attendees"], list)
    assert len(d["attendees"]) == 1
    assert d["attendees"][0]["attendee"]["attendee_id"] == "att_solo"
    assert "markdown" in d
    assert isinstance(d["markdown"], str)
    assert d["rendered_at"] > 0


def test_debrief_action_returns_full_payload(tars_home: Path) -> None:
    store = get_lab_store()
    store.create_workshop(name="Action", workshop_id="ws_act")
    store.enroll(
        workshop_id="ws_act",
        display_name="Carol",
        attendee_id="att_c",
    )
    res = asyncio.run(
        lab_workshop_debrief_action({"workshop_id": "ws_act"})
    )
    assert res["ok"] is True
    assert res["debrief"]["workshop"]["workshop_id"] == "ws_act"
    assert "markdown" in res["debrief"]
    assert res["debrief"]["leaderboard"]["attendees_total"] == 1
