"""Tests for the live Tauri updater channel HTTP surface.

The channel JSON is consumed by ``tauri-plugin-updater`` and must
stay in lock-step with ``/api/product/downloads`` (both pull from
the same in-memory :class:`DownloadManifest`). This suite covers:

1. The bridge primitives (``known_targets``, ``target_to_os_arch``,
   ``build_channel_from_release``).
2. The HTTP endpoints
   (``GET /updates/{target}/{version}.json``,
   ``GET /api/product/updater/targets``):
   - 200 with the expected wire shape for every supported target
   - 404 for unknown targets
   - 404 when no release exists for the target's OS
   - cache + custom headers
   - lock-step with ``/api/product/downloads``
"""

from __future__ import annotations

from pathlib import Path

import pytest


# ---------------------------------------------------------------------
# Bridge primitives
# ---------------------------------------------------------------------


def test_known_targets_cover_every_supported_os_arch():
    from backend.core.product.updater import known_targets

    targets = set(known_targets())
    # Every Tauri slug we publish should appear here. Adding a
    # new target without updating known_targets would silently
    # drop it from the live endpoint.
    expected = {
        "darwin-aarch64",
        "darwin-x86_64",
        "darwin-universal",
        "windows-x86_64",
        "windows-aarch64",
        "windows-i686",
        "linux-x86_64",
        "linux-aarch64",
    }
    assert targets == expected


def test_target_to_os_arch_maps_known_slugs():
    from backend.core.product.updater import target_to_os_arch

    assert target_to_os_arch("darwin-aarch64") == ("macos", "arm64")
    assert target_to_os_arch("darwin-x86_64") == ("macos", "x64")
    assert target_to_os_arch("windows-x86_64") == ("windows", "x64")
    assert target_to_os_arch("linux-aarch64") == ("linux", "arm64")


def test_target_to_os_arch_returns_none_for_unknown():
    from backend.core.product.updater import target_to_os_arch

    assert target_to_os_arch("haiku-aarch64") is None
    assert target_to_os_arch("") is None
    assert target_to_os_arch("darwin") is None


def _build_release_entry(version: str = "1.0.0", *, with_macos: bool = True):
    """Build a synthetic ``ReleaseEntry`` for tests without
    touching disk state. Mirrors the shape generated by the
    publish CLI."""

    from backend.core.product.manifest import (
        ReleaseArtifact,
        ReleaseEntry,
    )

    artifacts: list[ReleaseArtifact] = []
    if with_macos:
        artifacts.extend(
            [
                ReleaseArtifact(
                    os="macos",
                    arch="arm64",
                    kind="dmg",
                    filename=f"TARS-{version}-arm64.dmg",
                    url=f"https://example.com/{version}/arm64.dmg",
                ),
                ReleaseArtifact(
                    os="macos",
                    arch="x64",
                    kind="dmg",
                    filename=f"TARS-{version}-x64.dmg",
                    url=f"https://example.com/{version}/x64.dmg",
                ),
            ]
        )
    artifacts.append(
        ReleaseArtifact(
            os="windows",
            arch="x64",
            kind="msi",
            filename=f"TARS-{version}.msi",
            url=f"https://example.com/{version}/setup.msi",
        )
    )
    return ReleaseEntry(
        version=version,
        channel="stable",
        released_at="2026-05-01T00:00:00Z",
        notes="Test build",
        artifacts=tuple(artifacts),
    )


def test_build_channel_from_release_full_view():
    from backend.core.product.updater import build_channel_from_release

    entry = _build_release_entry("1.0.0")
    channel = build_channel_from_release(entry)
    assert channel.version == "1.0.0"
    assert channel.notes == "Test build"
    assert channel.pub_date == "2026-05-01T00:00:00Z"
    targets = {p.target for p in channel.platforms}
    assert {"darwin-aarch64", "darwin-x86_64", "windows-x86_64"} <= targets


def test_build_channel_from_release_filters_to_target():
    from backend.core.product.updater import build_channel_from_release

    entry = _build_release_entry("1.0.0")
    channel = build_channel_from_release(entry, target="darwin-aarch64")
    assert len(channel.platforms) == 1
    assert channel.platforms[0].target == "darwin-aarch64"
    assert channel.platforms[0].url.endswith("arm64.dmg")


def test_build_channel_from_release_target_with_no_artifact_returns_empty():
    from backend.core.product.updater import build_channel_from_release

    # Entry only ships a windows MSI — asking for darwin-aarch64
    # should produce a channel with no platforms.
    entry = _build_release_entry("1.0.0", with_macos=False)
    channel = build_channel_from_release(entry, target="darwin-aarch64")
    assert len(channel.platforms) == 0


def test_build_channel_uses_pub_date_from_release():
    from backend.core.product.updater import build_channel_from_release
    from backend.core.product.manifest import ReleaseEntry, ReleaseArtifact

    entry = ReleaseEntry(
        version="9.9.9",
        channel="stable",
        released_at="2030-01-15T08:00:00Z",
        notes=None,
        artifacts=(
            ReleaseArtifact(
                os="macos",
                arch="arm64",
                kind="app",
                filename="TARS.app.tar.gz",
                url="https://example.com/9.9.9/app.tar.gz",
            ),
        ),
    )
    channel = build_channel_from_release(entry)
    assert channel.pub_date == "2030-01-15T08:00:00Z"
    # No notes in the release → empty string in the channel.
    assert channel.notes == ""


def test_build_channel_picks_up_sidecar_signatures(tmp_path: Path):
    from backend.core.product.updater import build_channel_from_release
    from backend.core.product.manifest import ReleaseEntry, ReleaseArtifact

    artifact_path = tmp_path / "TARS-1.2.3-arm64.dmg"
    artifact_path.write_bytes(b"binary")
    sig_path = tmp_path / "TARS-1.2.3-arm64.dmg.sig"
    sig_path.write_text("untrusted-comment\n<base64sig>\n", encoding="utf-8")

    entry = ReleaseEntry(
        version="1.2.3",
        channel="stable",
        released_at="2026-06-01T00:00:00Z",
        notes=None,
        artifacts=(
            ReleaseArtifact(
                os="macos",
                arch="arm64",
                kind="dmg",
                filename="TARS-1.2.3-arm64.dmg",
                url="https://example.com/1.2.3/arm64.dmg",
            ),
        ),
    )
    channel = build_channel_from_release(
        entry, target="darwin-aarch64", artifacts_dir=tmp_path
    )
    assert len(channel.platforms) == 1
    sig = channel.platforms[0].signature
    assert "<base64sig>" in sig


# ---------------------------------------------------------------------
# HTTP fixture
# ---------------------------------------------------------------------


@pytest.fixture
def client(monkeypatch, tmp_path):
    monkeypatch.setenv("MEEET_STORE", "disabled")
    monkeypatch.setenv("MEMORY_STORE", "disabled")
    monkeypatch.setenv("TARS_CHAT_DB_PATH", str(tmp_path / "chat.sqlite"))

    from fastapi.testclient import TestClient
    from web_extras.app import app

    return TestClient(app)


# ---------------------------------------------------------------------
# /api/product/updater/targets
# ---------------------------------------------------------------------


def test_http_known_targets_returns_full_matrix(client):
    resp = client.get("/api/product/updater/targets")
    assert resp.status_code == 200
    body = resp.json()
    assert body["ok"] is True
    targets = set(body["targets"])
    assert "darwin-aarch64" in targets
    assert "linux-x86_64" in targets
    assert "windows-x86_64" in targets


def test_http_known_targets_is_cacheable(client):
    resp = client.get("/api/product/updater/targets")
    assert "cache-control" in {k.lower() for k in resp.headers.keys()}
    cache = resp.headers.get("cache-control", "")
    assert "public" in cache
    assert "max-age" in cache


# ---------------------------------------------------------------------
# /updates/{target}/{version}.json
# ---------------------------------------------------------------------


def test_http_updater_channel_returns_tauri_shape(client):
    resp = client.get("/updates/darwin-aarch64/0.0.0.json")
    assert resp.status_code == 200
    body = resp.json()
    assert "version" in body
    assert "pub_date" in body
    assert "platforms" in body
    assert "darwin-aarch64" in body["platforms"]
    plat = body["platforms"]["darwin-aarch64"]
    # Tauri requires both fields on every platform entry.
    assert "url" in plat
    assert "signature" in plat
    # Custom header lets monitors filter logs by target.
    assert resp.headers.get("x-tars-updater-target") == "darwin-aarch64"


def test_http_updater_channel_serves_each_known_target(client):
    """Every target advertised by ``known_targets`` must either
    serve a 200 (default manifest covers it) or a 404 with a
    ``no_release_for_target`` detail (default manifest skips it).

    No target should crash, hit an unknown_target 404, or return
    a body without the Tauri-required keys."""

    targets_resp = client.get("/api/product/updater/targets")
    targets = targets_resp.json()["targets"]

    for target in targets:
        resp = client.get(f"/updates/{target}/0.0.0.json")
        assert resp.status_code in (200, 404), f"target={target}"
        if resp.status_code == 200:
            body = resp.json()
            assert "version" in body
            assert "platforms" in body
            assert target in body["platforms"]
        else:
            assert resp.json()["detail"] == "no_release_for_target"


def test_http_updater_channel_unknown_target_returns_404(client):
    resp = client.get("/updates/haiku-aarch64/0.0.0.json")
    assert resp.status_code == 404
    assert resp.json()["detail"] == "unknown_target"


def test_http_updater_channel_path_with_pre_release_version(client):
    """The ``current_version`` segment is informational — Tauri
    embeds the installed build's semver. We accept anything that
    doesn't break path routing (no slashes / .json suffix)."""

    resp = client.get(
        "/updates/darwin-aarch64/0.1.0-alpha.5%2Bbuild.123.json"
    )
    assert resp.status_code in (200, 404)


def test_http_updater_channel_lock_step_with_downloads(client):
    """The Tauri channel must report the same version as
    ``/api/product/downloads/latest`` for the same OS — that's
    the lock-step contract."""

    downloads = client.get(
        "/api/product/downloads/latest?os=macos"
    ).json()
    expected_version = downloads["release"]["version"]

    channel = client.get("/updates/darwin-aarch64/0.0.0.json").json()
    assert channel["version"] == expected_version


def test_http_updater_channel_caches_for_one_minute(client):
    resp = client.get("/updates/darwin-aarch64/0.0.0.json")
    assert resp.status_code in (200, 404)
    if resp.status_code == 200:
        cache = resp.headers.get("cache-control", "")
        assert "max-age=60" in cache


def test_http_updater_channel_pulls_from_load_manifest(monkeypatch, client):
    """When ``load_manifest`` returns an entry with no artifact for
    the requested OS, the endpoint should 404 instead of returning
    an empty platforms map (which would confuse Tauri)."""

    from backend.core.product.manifest import (
        DownloadManifest,
        ReleaseArtifact,
        ReleaseEntry,
        CONTRACT_VERSION,
    )
    from web_extras.routers import product as product_router

    fake_entry = ReleaseEntry(
        version="2.0.0",
        channel="stable",
        released_at="2026-05-01T00:00:00Z",
        notes=None,
        artifacts=(
            ReleaseArtifact(
                os="windows",
                arch="x64",
                kind="msi",
                filename="TARS-2.0.0.msi",
                url="https://example.com/2.0.0/setup.msi",
            ),
        ),
    )
    fake_manifest = DownloadManifest(
        product="tars",
        contract_version=CONTRACT_VERSION,
        channel="stable",
        released_at="2026-05-01T00:00:00Z",
        releases=(fake_entry,),
        source="defaults",
    )
    monkeypatch.setattr(
        product_router, "load_manifest", lambda: fake_manifest
    )

    # macOS has no artifact in the fake manifest → 404.
    resp = client.get("/updates/darwin-aarch64/0.0.0.json")
    assert resp.status_code == 404

    # Windows is present → 200.
    resp = client.get("/updates/windows-x86_64/0.0.0.json")
    assert resp.status_code == 200
    body = resp.json()
    assert body["version"] == "2.0.0"
    assert body["platforms"]["windows-x86_64"]["url"].endswith("setup.msi")


def test_http_updater_channel_signature_passthrough(monkeypatch, client, tmp_path: Path):
    """If a sidecar ``.sig`` exists alongside the artifact bytes,
    the channel surfaces its content verbatim. We can't easily
    drop a sidecar onto the live ``meeet.world`` URL, so the
    bridge runs in two modes — without ``artifacts_dir`` (HTTP
    serves "no signature") and with one (CLI mode). This test
    pins the HTTP behaviour: signature is always an empty string
    when the manifest doesn't include one explicitly."""

    resp = client.get("/updates/darwin-aarch64/0.0.0.json")
    if resp.status_code == 200:
        body = resp.json()
        sig = body["platforms"]["darwin-aarch64"]["signature"]
        # The default-bundle manifest doesn't ship signatures, so
        # the live endpoint surfaces empty strings.
        assert sig == ""
