#!/usr/bin/env bash
# RUN-PERF-SUITE.command — W266 final v10.0 GA perf gate.
#
# Runs the 5 hottest-path benchmarks under tests/perf/, then renders
# docs/PERF_REPORT_v10.0.md with the p50/p95/p99 numbers and SLO
# pass/fail status for each. Aborts (exit 1) if any SLO is breached.
#
# Run from the repo root or by double-clicking the file from Finder.
#   bash scripts/RUN-PERF-SUITE.command

set -u

cd "$(dirname "${BASH_SOURCE[0]}")/.."
REPO="$(pwd)"
LOG="${REPO}/.RUN-PERF-SUITE.txt"

exec > >(tee -a "$LOG") 2>&1

if [ -t 1 ]; then
  G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; B=$'\033[34m'; D=$'\033[2m'; X=$'\033[0m'
else
  G=""; R=""; Y=""; B=""; D=""; X=""
fi

echo "=== RUN-PERF-SUITE.command at $(date -u +%Y-%m-%dT%H:%M:%SZ) ==="
echo "repo: ${REPO}"

# Five benches, in dependency-light to dependency-heavy order so a
# regression in the cheaper paths short-circuits the more expensive
# ones (saves minutes when chasing a P0 perf bug).
BENCHES=(
  "bench_voice_command"
  "bench_usage_metering"
  "bench_composer_plan"
  "bench_audit_timeline"
  "bench_chat"
)

PYTHON="${PYTHON:-python3}"
if [ -x "${REPO}/.venv/bin/python" ]; then
  PYTHON="${REPO}/.venv/bin/python"
  echo "${D}using venv python: ${PYTHON}${X}"
fi

# Detect pytest-benchmark availability — purely cosmetic, the bench
# files themselves don't require it.
if "${PYTHON}" -c "import pytest_benchmark" 2>/dev/null; then
  echo "${D}pytest-benchmark present — passing through.${X}"
else
  echo "${Y}pytest-benchmark not installed; benches will use the asyncio.gather fallback.${X}"
fi

# Wipe stale results so the report can't accidentally read yesterday's.
rm -rf "${REPO}/tests/perf/.results"
mkdir -p "${REPO}/tests/perf/.results"

FAILED=()
PASSED=()

for bench in "${BENCHES[@]}"; do
  echo ""
  echo "${B}── running ${bench} ──${X}"
  if "${PYTHON}" -m pytest "tests/perf/${bench}.py" -m perf -q --no-header --tb=short; then
    echo "${G}✓${X} ${bench} passed"
    PASSED+=("${bench}")
  else
    echo "${R}✗${X} ${bench} FAILED"
    FAILED+=("${bench}")
  fi
done

# ── Render docs/PERF_REPORT_v10.0.md ───────────────────────────────
echo ""
echo "${B}── rendering docs/PERF_REPORT_v10.0.md ──${X}"

REPORT="${REPO}/docs/PERF_REPORT_v10.0.md"
mkdir -p "${REPO}/docs"

"${PYTHON}" - <<'PY_RENDER'
import json, os
from pathlib import Path
from datetime import datetime, timezone

repo = Path(os.environ.get("REPO", os.getcwd()))
results_dir = repo / "tests" / "perf" / ".results"
out = repo / "docs" / "PERF_REPORT_v10.0.md"

order = [
    "bench_chat",
    "bench_voice_command",
    "bench_usage_metering",
    "bench_audit_timeline",
    "bench_composer_plan",
]
slo_table = {
    "bench_chat":            "p95 < 2.5s (100 concurrent)",
    "bench_voice_command":   "p95 < 800ms (50 concurrent)",
    "bench_usage_metering":  "1000/s sustained, no drops",
    "bench_audit_timeline":  "p95 < 200ms (10k receipts)",
    "bench_composer_plan":   "p95 < 4s (20 concurrent)",
}

rows = []
any_fail = False
any_missing = False
for name in order:
    f = results_dir / f"{name}.json"
    if not f.exists():
        rows.append((name, None))
        any_missing = True
    else:
        rows.append((name, json.loads(f.read_text())))

now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

lines = []
lines.append("# TARS v10.0 — Performance Report")
lines.append("")
lines.append(f"> Generated by `scripts/RUN-PERF-SUITE.command` at {now}.")
lines.append("> One row per benchmark. **passed = p95 within SLO target.**")
lines.append("")
lines.append("## Summary")
lines.append("")
lines.append("| Bench | SLO target | p50 | p95 | p99 | Result |")
lines.append("|---|---|---:|---:|---:|:--:|")
for name, row in rows:
    slo = slo_table[name]
    if row is None:
        lines.append(f"| `{name}` | {slo} | — | — | — | NOT RUN |")
        any_fail = True
        continue
    p50 = f"{row['p50_ms']:.1f}ms"
    p95 = f"{row['p95_ms']:.1f}ms"
    p99 = f"{row['p99_ms']:.1f}ms"
    if row["passed"]:
        verdict = "PASS"
    else:
        verdict = "FAIL"
        any_fail = True
    lines.append(f"| `{name}` | {slo} | {p50} | {p95} | {p99} | {verdict} |")

lines.append("")
lines.append("## Per-bench detail")
lines.append("")
for name, row in rows:
    lines.append(f"### `{name}`")
    lines.append("")
    if row is None:
        lines.append("Bench did not produce a result file. Re-run "
                     "`bash scripts/RUN-PERF-SUITE.command`; if the failure persists, "
                     "the test itself raised before recording — open `.RUN-PERF-SUITE.txt`.")
        lines.append("")
        continue
    lines.append(f"- **SLO target:** {slo_table[name]}")
    lines.append(f"- **Samples:** {row['samples']}")
    lines.append(f"- **p50/p95/p99/max:** {row['p50_ms']:.1f}ms / {row['p95_ms']:.1f}ms / {row['p99_ms']:.1f}ms / {row['max_ms']:.1f}ms")
    if "throughput_per_s" in row:
        lines.append(f"- **Throughput:** {row['throughput_per_s']}/s")
    if "concurrency" in row:
        lines.append(f"- **Concurrency:** {row['concurrency']}")
    if "drops" in row:
        lines.append(f"- **Drops:** {row['drops']}")
    if row.get("description"):
        lines.append(f"- **Notes:** {row['description']}")
    lines.append(f"- **Result:** {'PASS' if row['passed'] else 'FAIL — SLO breached'}")
    lines.append("")

lines.append("---")
lines.append("")
if any_fail or any_missing:
    lines.append("**REGRESSION** — one or more SLOs breached. See the per-bench detail above; ")
    lines.append("each bench's assertion message in `.RUN-PERF-SUITE.txt` includes a suggested fix.")
    lines.append("Do **not** tag v10.0 GA until every row reads PASS.")
else:
    lines.append("**All five SLOs green.** Perf gate is clear for v10.0 GA.")
lines.append("")

out.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {out}")
PY_RENDER

# ── Verdict ────────────────────────────────────────────────────────
echo ""
if [ "${#FAILED[@]}" -gt 0 ]; then
  echo "${R}=== REGRESSION ===${X}"
  echo "${R}Failed benches: ${FAILED[*]}${X}"
  echo ""
  echo "${R}Suggested fixes are printed in each bench's assertion message.${X}"
  echo "${R}Full log: ${LOG}${X}"
  echo "${R}Report:   docs/PERF_REPORT_v10.0.md${X}"
  echo ""
  echo "${R}Do NOT tag v10.0 GA until all five SLOs green.${X}"
  exit 1
fi

echo "${G}=== ALL FIVE SLOs GREEN ===${X}"
echo "${G}Perf gate clear — v10.0 GA can proceed.${X}"
echo ""
echo "Report:  docs/PERF_REPORT_v10.0.md"
echo "Log:     ${LOG}"
exit 0
